Add documentation for mihonapp/mihon #420
mihonapp/website pull request #47
Opened 2024-03-22 16:06 UTC by sirlag

Updated FAQ section for the upcoming updates screen as per inclusion in [#420](https://github.com/mihonapp/mihon/pull/420)

2024-03-23 10:32 UTC, loocool2 requested changes
Looks pretty good but there are a few places that I think should be changed to be clearer.

2024-03-23 10:32 UTC, loocool2 commented on website/src/docs/faq/upcoming.md
> +In order to reduce strain on our partners and save user bandwidth, Mihon tries to estimate when chapter updates will be available, and only once that time has past include that series in automatic up
```suggestion
In order to reduce strain on sources and save user bandwidth, Mihon tries to estimate when chapter updates will be available, and only once that time has passed, include that series in automatic updates.
```
You shouldn't refer to sources as partners as we don't have any relationship with sources and in my opinion referring to them as partners implies one. Also a little grammar change.

2024-03-23 10:32 UTC, loocool2 commented on website/src/docs/faq/upcoming.md
> +Smart updates determine time of chapter updates based on the time between currently released chapters. Sources that provide incorrect update dates, periods of hiatus, or bursts of short chapters may
```suggestion
Smart updates determine time of chapter updates based on the time between currently released chapters. Sources that provide incorrect update dates, periods of hiatus, or update in batches may result in the estimate seeming off. As more chapters are released, the schedule should become more accurate.
```
batch updates is probably a better way to refer this. Latter change should be a little more clear on what difference is.

2024-03-23 12:38 UTC, sirlag commented
Seems like good changes, thanks @loocool2

2024-03-24 18:45 UTC, Soitora commented
Maybe place the page at a subpage to Updates
`/docs/faq/updates/upcoming` rather than `/docs/faq/upcoming`

And then rename the page to just Upcoming

Rest looks fine to me, albeit maybe a bit too technically answered

2024-03-24 20:16 UTC, sirlag commented
@Soitora Only issue with that suggestion is we don't have a `/updates` currently. We could create one and put the info from the `!smartupdates` command from the discord into it.

2024-03-24 20:28 UTC, Soitora commented
> @Soitora Only issue with that suggestion is we don't have a `/updates` currently. We could create one and put the info from the `!smartupdates` command from the discord into it.

I can look into adding it tomorrow or something, unless you wanna make a simple PR for it

2024-03-26 18:21 UTC, Soitora approved these changes

2024-03-28 19:03 UTC, merged